---
- name:    restart nslcd messagebus oddjobd nscd service for CentOS
  become:  yes
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - nslcd
    - messagebus
    - oddjobd
    - nscd

