---
- name: change /etc/apt/sources.list for ubuntu
  become: yes
  template: src=templates/apt_sources/sources.list.ubuntu.j2 dest=/etc/apt/sources.list owner=root group=root mode=0644
  when:    ansible_distribution == 'Ubuntu'

- name: change /etc/apt/sources.list
  become: yes
  template: src=templates/apt_sources/sources.list.j2 dest=/etc/apt/sources.list owner=root group=root mode=0644
  when:    ansible_distribution == 'Debian'

- name: add key for repository server
  become: yes
  shell: "wget -O - http://{{ debian_repo }}/debian/keyFile | apt-key add -"
  when:    ansible_distribution == 'Debian'

- name:    get pacakage to set zabbix repository
  become:  yes
  get_url: url=http://repo.zabbix.com/zabbix/2.4/debian/pool/main/z/zabbix-release/zabbix-release_2.4-1+jessie_all.deb dest=/usr/local/src
  when:    ansible_distribution == 'Debian'

- name:    install pacakage to set zabbix repository
  become:  yes
  apt:     deb=/usr/local/src/zabbix-release_2.4-1+jessie_all.deb
  when:    ansible_distribution == 'Debian'

