- name: disable service
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - "unbound"
    - "kdump"
    - "wpa_supplicant"

- name: disable service for CentOS7
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - "chronyd"
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == "7"
