---
- name: set hostname to /etc/hosts for ubuntu
  become: yes
  lineinfile:
    dest: /etc/hosts
    insertafter: '127.0.0.1 localhost'
    line: '127.0.0.1 {{ ansible_hostname }}'
  when: ansible_distribution == 'Ubuntu'

