---
- include: hostname.yml
  tags: hostname
- include: resolv.yml
  tags: resolv
- include: apt_sources.yml
  tags: apt_sources
- include: yum_repo.yml
  tags: yum_repo
- include: selinux.yml
  tags: selinux
- include: epel.yml
  tags: epel
- include: pkg_update.yml
  tags: pkg_update
- include: ubuntu_security.yml
  tags: ubuntu_security
- include: timezone.yml
  tags: timezone
- include: vmware-tools.yml
  tags: vmware-tools
- include: utils.yml
  tags: utils
- include: zabbix.yml
  tags: zabbix
- include: ldap.yml
  tags: ldap
- include: sshd.yml
  tags: sshd
- include: user.yml
  tags: user
- include: logrotate.yml
  tags: logrotate
- include: history.yml
  tags: history
- include: editor.yml
  tags: editor
- include: kernel.yml
  tags: kernel
- include: hosts.yml
  tags: hosts
- include: rsyslog.yml
  tags: rsyslog
- include: tuned.yml
  tags: tuned
- include: disable_service.yml
  tags: disable_service
- include: locale.yml
  tags: locale
- include: td-agent.yml
  tags: td-agent
  when:    ansible_os_family == "RedHat"
- include: open_files_limit.yml
  tags: open_files_limit
- include: delete_sshkey.yml                                                                               
  tags: delete_sshkey
