---
- name: add /etc/yum.repos.d/CentOS-Base.repo for CentOS7
  become: yes
  template: src=templates/yum_repo/CentOS-Base.repo.j2 dest=/etc/yum.repos.d/CentOS-Base.repo owner=root group=root mode=0644
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: update yum.conf
  become:  yes
  replace:
    dest: "/etc/yum.conf"
    regexp: '^exclude=kernel\.\*'
    replace: '#exclude=kernel.*'
    backup: "yes"
